linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]

run:
  timeout: 5m
